### ISSUE TITLE
Blocking reasons

### ISSUE THREAD

**Issue by ajanvier** [tootcafe/blocked-instances#1]
Hi,

Could you please add the reasons for the bloking of these instances next to them ?
It would help the other instances admins to know why they should be blocked.

Thank you !

**Comment by nolanlawson** [comment]
I'm sorry, I am basically going off of the toot.cat admin's words. My policy is "shoot first, ask questions later" because I want to protect my community.

Honestly I haven't even had time yet to evaluate them. I am still working on many many other issues in my community.

**Comment by Pajn** [comment]
In https://cybre.space/users/chr/updates/2616
>- freezepeach.xyz
>- rainbowdash.net
>- sealion.club
>- shitposter.club
>- social.headsca.la

Are mentioned

**Comment by nolanlawson** [comment]
Since this issue is getting some attention because I'm being subtooted about it, here's the statement I made on Mastodon which might not have gotten across because apparently I'm getting blocked by some folks (AFAICT):

> Hey folks, the truth is I have been running this server in my spare time on my own dime for the past few days, I've been getting barely any sleep, and I've been basically running on fumes all day.
>
> My priorities have been to get people in the door, make a welcoming and fun space, and get moderators recruited so that the bus factor is >1. I really will get to evaluating these instances; I just haven't had time. I'm being cautious because I'm new to Masto.

**Comment by nolanlawson** [comment]
BTW thanks @Pajn, I like the cybre.space admin a lot and so I consider their recommendation another point in favor of blocking. Note that the cybre.space list of instances is a subset of our list, so if any are candidates for un-blocking it would probably be the diff between the two since they only have one mark against them and not two.

Also based on the comments in the post it seems they based their decision not on the toot.cat list but on the "volume of concerning content coming" from those instances. So seems like 2 truly independent marks against that shared subset.

**Comment by nolanlawson** [comment]
Fixed by #5, please let me know if I mis-evaluated an instance. Thanks!
