### ISSUE TITLE
social.homunyan.com falsely classified as "child pornography"

### ISSUE THREAD

**Issue by rainyday** [tootcafe/blocked-instances#19]
I saw my instance was added due to being on dzuk's blocklist. It's on dzuk's list under "child pornography" for hosting a this image: https://social.homunyan.com/@ZettaiRyouiki/803214 which while admittedly sexually suggestive, is a drawing of a fully clothed adult. As such I fail to see how this constitutes child pornography or lolicon by any definition of these terms. If your intent is to block instances that allow any sexually suggestive images then that's your choice but if you've added my instance under the (mistaken) impression that we host child pornography then I would ask that you reconsider. I'd also suggest you place more scrutiny on block suggestions you get from other users/server admins as a number of dzuk's blocks are pretty suspect.

**Comment by nolanlawson** [comment]
These are gray-zone areas, and it's hard to make an uncontroversial judgment. What legal in one country may be illegal in another, and what's taboo in one group may be considered mundane in another.

However, even just the act of moderating this stuff can either put me in jail or damage me psychologically, so obviously I'm not inclined to go out and do a thorough analysis of various instances and spend a lot of my mental energy pondering what constitutes sexualized depictions of children and what doesn't.

That said, I'm ambivalent about turning blocklists into hearsay-based slander-as-a-service (which I've been accused of in the past), which is why I just noted social.homunyan.com as "advice of dzuk." Also, I did take some effort to evaluate social.homunyan.com, and I would prefer to continue silencing. This is mostly based on my feeling of what the toot.cafe community would prefer: i.e. more work-safe content, less gray-zone content. Thanks for understanding!

**Comment by rainyday** [comment]
This isn't a "gray zone area" unless you're in Saudi Arabia, depictions of fully clothed adults are not illegal. Obviously you're free to decide what you want on your instance, but have the decency not to lie about your reasons.
