### ISSUE TITLE
Another attempt at a replacement for "Free Speech Zone"

### ISSUE THREAD

**Issue by Chootin** [tootcafe/blocked-instances#26]
Would "Unmoderated Speech Zone" be an appropriate replacement?

**Comment by WorldMaker** [comment]
Why bother beating around the bush at all? Call it what it is: "Hate Speech Allowed".

**Comment by Gartral** [comment]
how about "Unfederated DMZ"?

**Comment by WorldMaker** [comment]
Isn't that the opposite description? The problem is that those instances are federated, and relatively militia-ed (not quite the same as militarized, certainly, but they point is that they are lawless like the old west, not lawless like a peace treaty enforced peace keeping zone). Hence why they should be blocked.

**Comment by nolanlawson** [comment]
Now that I think about it, I think both "free speech zone" and "unmoderated speech zone" imply that there is zero-moderation on these instances, which is probably not the case. More likely, their level of moderation and what's considered inappropriate is just different from toot.cafe's.

I'm not happy with either term, but I think for now the name seems about right. As a side note, I'm considering taking this discussion off of GitHub because it doesn't seem like the right venue for this kind of stuff, which always has to deal with gray zones and fuzzy areas and nebulous "he said, she said" scenarios.
